### ISSUE TITLE
APR27 - Smallest String With Swaps Challenge Solution

### ISSUE THREAD

**Issue by Rakesh9100** [utkarsh006/LeetCode-Grind#117]
### Description

I would add APR27 Challenge "Smallest String With Swaps" Solution.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
Already taken by another contributor

**Comment by Rakesh9100** [comment]
> Already taken by another contributor

I have changed the issue, so reopen.
