### ISSUE TITLE
AUG 2 :  Kth Smallest Element in a Sorted Matrix

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#121]
### Description

Given an n x n matrix where each of the rows and columns is sorted in ascending order, return the kth smallest element in the matrix.

Note that it is the kth smallest element in the sorted order, not the kth distinct element.

You must find a solution with a memory complexity better than O(n2).

Example 1:

Input: matrix = [[1,5,9],[10,11,13],[12,13,15]], k = 8

Output: 13

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@Shweta2024 Issue closed since it wasn't completed in the given time frame.

**Comment by surjyaneeh** [comment]
@utkarsh006, @gurjeetsinghvirdee I want to work on this issue, do I have to create the same issue or you can reopen it once?
