### ISSUE TITLE
AUG 5 :  Combination Sum IV

### ISSUE THREAD

**Issue by surjyaneeh** [utkarsh006/LeetCode-Grind#135]
### Description

Given an array of distinct integers nums and a target integer target, return the number of possible combinations that add up to target.

The test cases are generated so that the answer can fit in a 32-bit integer.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @surjyaneeh
