### ISSUE TITLE
August 7:Daily Leetcode challenge

### ISSUE THREAD

**Issue by deepshikha2708** [utkarsh006/LeetCode-Grind#140]
### Description

1220. Count Vowels Permutation
Hard

2078

143

Add to List

Share
Given an integer n, your task is to count how many strings of length n can be formed under the following rules:

Each character is a lower case vowel ('a', 'e', 'i', 'o', 'u')
Each vowel 'a' may only be followed by an 'e'.
Each vowel 'e' may only be followed by an 'a' or an 'i'.
Each vowel 'i' may not be followed by another 'i'.
Each vowel 'o' may only be followed by an 'i' or a 'u'.
Each vowel 'u' may only be followed by an 'a'.
Since the answer may be too large, return it modulo 10^9 + 7.

![image](https://user-images.githubusercontent.com/80972038/183306040-c420c15b-6820-42d7-9431-207d8d244209.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by deepshikha2708** [comment]
@utkarsh006 plz assign me this issue

**Comment by utkarsh006** [comment]
@deepshikha2708 Close the issue by today itself.

**Comment by deepshikha2708** [comment]
I am so sorry I had been inactive for the past 2 days, due to some personal issues I couldnt contribute in any projects. I will try to complete it by today or at most by tomorrow.

**Comment by coderSuren** [comment]
@utkarsh006 I would like to work on this issue. please assign this to me.
