### ISSUE TITLE
Update Jun 17 Issue

### ISSUE THREAD

**Issue by deepshikha2708** [utkarsh006/LeetCode-Grind#141]
### Description

![image](https://user-images.githubusercontent.com/80972038/183306549-576bc290-0497-4fc6-8165-77ec9871622e.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by deepshikha2708** [comment]
@utkarsh006 please assign me this issue

**Comment by utkarsh006** [comment]
@deepshikha2708 You can create PR for previous issue then only this can be assigned.

**Comment by deepshikha2708** [comment]
@utkarsh006 can you please assign me this issue
