### ISSUE TITLE
AUG 8 : Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#142]
### Description

Given an integer array nums, return the length of the longest strictly increasing subsequence.

A subsequence is a sequence that can be derived from an array by deleting some or no elements without changing the order of the remaining elements. For example, [3,6,2,7] is a subsequence of the array [0,3,1,6,2,2,7].

### Example

Input: nums = [10,9,2,5,3,7,101,18]

Output: 4

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue sir

**Comment by utkarsh006** [comment]
@Shweta2024 Close the issue by today itself.
