### ISSUE TITLE
JAN 24: Detect Capital 

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#143]
### Description

Will add the Jan 24 leetcode challenge solution

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @tanya-gupta25
