### ISSUE TITLE
AUG 10:  Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#145]
### Description

Will add 10 AUG Leetcode Daily Challenge Solution [Convert Sorted Array to Binary Search Tree](https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@tanya-gupta25 Make a PR for your previous issue first.

**Comment by utkarsh006** [comment]
@tanya-gupta25 Complete the PR by today

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 Complete the PR by today

Ya, will do that in an hour
