### ISSUE TITLE
Jan 25: Valid Mountain Array

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#152]
### Description

Add Jan 25: [Valid Mountain Array](https://leetcode.com/problems/valid-mountain-array/) from leetcode daily challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@tanya-gupta25 Solve this using Binary Search only !!

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 Solve this using Binary Search only !!

Okay, will do it
