### ISSUE TITLE
AUG 17 : Unique Morse Code Words 

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#174]
### Description

International Morse Code defines a standard encoding where each letter is mapped to a series of dots and dashes, as follows:

'a' maps to ".-",
'b' maps to "-...",
'c' maps to "-.-.", and so on.

Given an array of strings words where each word can be written as a concatenation of the Morse code of each letter.
Return the number of different transformations among all words we have.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue.

**Comment by utkarsh006** [comment]
@Shweta2024 Its a nice problem. Well, go ahead !!

**Comment by utkarsh006** [comment]
@Shweta2024 Complete the PR by today.

**Comment by surjyaneeh** [comment]
@utkarsh006 May I work on this issue?

**Comment by utkarsh006** [comment]
@surjyaneeh Yes you can work on this issue

**Comment by utkarsh006** [comment]
@surjyaneeh Complete the PR by today
