### ISSUE TITLE
Aug 23 Daily Challenge 

### ISSUE THREAD

**Issue by deepshikha2708** [utkarsh006/LeetCode-Grind#187]
### Description

![image](https://user-images.githubusercontent.com/80972038/186383139-9521703f-7ac5-40a5-ba5b-bf285b23351b.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by deepshikha2708** [comment]
@utkarsh006 can you assign me this issue?

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @deepshikha2708

**Comment by utkarsh006** [comment]
@deepshikha2708 Complete the PR by today 6PM

**Comment by surjyaneeh** [comment]
Hey, isn't the problem in the Screenshot of AUG 24?

**Comment by utkarsh006** [comment]
@surjyaneeh Would you like to take issue and complete it by today?

**Comment by surjyaneeh** [comment]
She made the wrong issue. this problem is already done by me. Kindly close this issue.
