### ISSUE TITLE
Aug 24 Daily Challenge 

### ISSUE THREAD

**Issue by deepshikha2708** [utkarsh006/LeetCode-Grind#194]
### Description

![image](https://user-images.githubusercontent.com/80972038/186632329-e5a07ed7-159c-4ef2-b288-be94cca0879c.png)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by deepshikha2708** [comment]
@utkarsh006 can you assign me this issue?

**Comment by surjyaneeh** [comment]
The problem in the Screenshot is of August 23.
@utkarsh006 may I work on the AUG 24 daily challenge?

**Comment by utkarsh006** [comment]
This issue has already been completed. @deepshikha2708 Stop creating such nuisances again and again.
