### ISSUE TITLE
Add approaches and complexities in JUNE -6,7,8

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#199]
### Description

- Will add question, examples, approaches and complexities in JUNE -6,7,8 daily challenge
- June 6- [Intersection of Two Linked Lists](https://leetcode.com/problems/intersection-of-two-linked-lists/)
- June 7 -[Merge Sorted Array](https://leetcode.com/problems/merge-sorted-array/)
- june 8-[Remove Palindromic Subsequences](https://leetcode.com/problems/remove-palindromic-subsequences/)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
I am assigning it but kindly see other issues first which are unassigned.
