### ISSUE TITLE
AUG 27 : Max Sum of Rectangle No Larger Than K

### ISSUE THREAD

**Issue by coderSuren** [utkarsh006/LeetCode-Grind#206]
### Description

Will add solution for [AUG-27](https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/) Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by coderSuren** [comment]
@utkarsh006 Please assign this issue to me

**Comment by tanya-gupta25** [comment]
Assign me
