### ISSUE TITLE
MARCH 16: Validate Stack Sequences

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#218]
### Description

Will add March 16 Daily challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
Take issue no. #206

**Comment by tanya-gupta25** [comment]
> Take issue no. #206

But someone else wants that issue to be assigned

**Comment by utkarsh006** [comment]
I am saying take issue no #206. The guy who created this is not regularly contributing.
