### ISSUE TITLE
Make new folder as SEPT CHALLENGES 

### ISSUE THREAD

**Issue by utkarsh006** [utkarsh006/LeetCode-Grind#224]
### Description

Make a folder for September challenges, add Sept1 Problem and along with it update the README as done in previous folders.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by nishkarsh800** [comment]
assign me this issue
