### ISSUE TITLE
Add a problem and update README.md

### ISSUE THREAD

**Issue by deepshikha2708** [utkarsh006/LeetCode-Grind#234]
### What happened?

![image](https://user-images.githubusercontent.com/80972038/194376302-56bd8888-d478-4b29-b320-1b6720a93450.png)

### How can we reproduce this bug?

can I add the september challenge here and thereby add one daily leetcode challenge for september?

**Comment by utkarsh006** [comment]
@deepshikha2708 Also add a problem of your choice. Since in hacktoberfest the PR's of low contributions won't be accepted.

**Comment by utkarsh006** [comment]
@deepshikha2708 Kindly update this issue and raise a PR for both.
