### ISSUE TITLE
JULY 20 : Number of Matching Subsequences

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#26]
## Description
Given a string s and an array of strings words, return the number of words[i] that is a subsequence of s.

## Example

Input: s = "abcde", words = ["a","bb","acd","ace"]
Output: 3

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
@Shweta2024 Assigned u
