### ISSUE TITLE
Sept 28_	Remove Nth Node From End of List

### ISSUE THREAD

**Issue by Anjali-Chaudhary3** [utkarsh006/LeetCode-Grind#264]
### Description

**Description**
This contains the solution to the daily challenge of 28th September
(Remove Nth Node From End of List)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Anjali-Chaudhary3** [comment]
please assign this issue to me

**Comment by Jyotisaini-2001** [comment]
Hii, I want to contribute in Sept 28_ Remove Nth Node From End of List in cpp. please assign me.

**Comment by utkarsh006** [comment]
@Jyotisaini-2001 Create a new issue.

**Comment by Jyotisaini-2001** [comment]
> @Jyotisaini-2001 Create a new issue.

ok

**Comment by utkarsh006** [comment]
Share the meet link.
