### ISSUE TITLE
9th-October daily leetcode challenge

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#274]
## Two Sum IV - Input is a BST

Given the root of a Binary Search Tree and a target number k, return true if there exist two elements in the BST such that their sum is equal to the given target.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Shweta2024** [comment]
@utkarsh006 can you please assign this to me

**Comment by utkarsh006** [comment]
Sure Assigned :) Appreciated the proper format of making an issue.
