### ISSUE TITLE
17th October LeetCode Challenge

### ISSUE THREAD

**Issue by Adamya-Jha** [utkarsh006/LeetCode-Grind#276]
### Description

17th October LeetCode Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by vaibhv232** [comment]
hii sir/mam assign this to me

**Comment by utkarsh006** [comment]
@Premjeet1804 yes you can do this now.

**Comment by Anjali-Chaudhary3** [comment]
@utkarsh006 as this issue is still open . Can i contribute to it?

**Comment by utkarsh006** [comment]
@Premjeet1804 Submit the PR by today midnight.

**Comment by Premjeet1804** [comment]
sir i have already given

**Comment by Premjeet1804** [comment]
and it shows invalid ... even i thing i had submitted the required file as well

**Comment by utkarsh006** [comment]
@Anjali-Chaudhary3 Yeah go ahead.
