### ISSUE TITLE
18th October LeetCode Challenge

### ISSUE THREAD

**Issue by Adamya-Jha** [utkarsh006/LeetCode-Grind#277]
### Description

18th October LeetCode Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by vaibhv232** [comment]
hello sir, assign this to me

**Comment by Premjeet1804** [comment]
can i get this assigned to me

**Comment by utkarsh006** [comment]
@Premjeet1804 Create a new issue by yourself as they are assigned on FCFS(First Come First Serve) basis.

**Comment by Premjeet1804** [comment]
ok i am creating an issue on leetcode  weekly contest 315 is it okay sir....!
