### ISSUE TITLE
Leetcode weekly contest 315th

### ISSUE THREAD

**Issue by Premjeet1804** [utkarsh006/LeetCode-Grind#278]
### Description

All sloution of leetcode weekly contest 315th contest

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by ashish5433** [comment]
hey @Premjeet1804 please assign this to me

**Comment by utkarsh006** [comment]
@Premjeet1804 Before creating an issue, you must look that what this repo is about.
