### ISSUE TITLE
20th October Leetcode Challenge

### ISSUE THREAD

**Issue by nishkarsh800** [utkarsh006/LeetCode-Grind#283]
### Description

20th October Leetcode Challenge

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh2709** [comment]
@nishkarsh800 I would like to contribute. Pls, assign it to me.

**Comment by utkarsh006** [comment]
@utkarsh2709 Visit the issues which are unassigned.
