### ISSUE TITLE
Oct 23_Leetcode daily challenge

### ISSUE THREAD

**Issue by Anjali-Chaudhary3** [utkarsh006/LeetCode-Grind#289]
### Description

You have a set of integers s, which originally contains all the numbers from 1 to n. Unfortunately, due to some error, one of the numbers in s got duplicated to another number in the set, which results in repetition of one number and loss of another number.

You are given an integer array nums representing the data status of this set after the error.

Find the number that occurs twice and the number that is missing and return them in the form of an array.

Example 1:

Input: nums = [1,2,2,4]
Output: [2,3]

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Anjali-Chaudhary3** [comment]
@utkarsh006 please assign this issue to me

**Comment by ankitkumar0622** [comment]
Hi , can you please assign me this task .

**Comment by vanshikaa-agarwal** [comment]
I would like to work on this

**Comment by Vedant070401** [comment]
please assign this to me
