### ISSUE TITLE
JULY 22 : Partition List

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#38]
## Description 
Given the head of a linked list and a value x, partition it such that all nodes less than x come before nodes greater than or equal to x.
You should preserve the original relative order of the nodes in each of the two partitions.

Example 

![image](https://user-images.githubusercontent.com/75883328/180456006-c89da095-fb0e-425d-add0-c7b57b656813.png)

Input: head = [1,4,3,2,5,2], x = 3
Output: [1,2,2,4,3,5]

**Comment by Shweta2024** [comment]
@utkarsh006 sir please assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
Assigned it to u
