### ISSUE TITLE
JUN 13 : Triangle

### ISSUE THREAD

**Issue by surjyaneeh** [utkarsh006/LeetCode-Grind#48]
[Link](https://leetcode.com/problems/triangle/)

**Comment by utkarsh006** [comment]
@surjyaneeh Give chance to other Contributors also. Hope you understand !!

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Give chance to other Contributors also. Hope you understand !!

Okay. 😞 I can understand.
