### ISSUE TITLE
JULY-25 Find First and Last Position of Element in Sorted Array

### ISSUE THREAD

**Issue by Akanksha-Sen** [utkarsh006/LeetCode-Grind#53]
Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.

If target is not found in the array, return [-1, -1].

You must write an algorithm with O(log n) runtime complexity.

 

*Example 1:*

Input: nums = [5,7,7,8,8,10], target = 8
Output: [3,4]

**Comment by surjyaneeh** [comment]
@Akanksha-Sen It's July 25 I guess.

**Comment by Akanksha-Sen** [comment]
Yes its 25th.. sorry typing mistake

**Comment by utkarsh006** [comment]
@Akanksha-Sen Firstly change the title of the issue then you may issue. Also elaborate on your issue with the proper statement

**Comment by Akanksha-Sen** [comment]
updated.

**Comment by utkarsh006** [comment]
@Akanksha-Sen Complete the PR by today midnight else your issue will be closed.
