### ISSUE TITLE
July 21: Reverse Linkedlist II

### ISSUE THREAD

**Issue by tanya-gupta25** [utkarsh006/LeetCode-Grind#61]
[Reverse Linkedlist II](https://leetcode.com/problems/reverse-linked-list-ii/)

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by utkarsh006** [comment]
@tanya-gupta25 Make a Pr by today midnight.

**Comment by tanya-gupta25** [comment]
> @tanya-gupta25 Make a Pr by today midnight.

Sure I will
