### ISSUE TITLE
Update MAR 30_Search a 2d matrix.cpp

### ISSUE THREAD

**Issue by surjyaneeh** [utkarsh006/LeetCode-Grind#62]
Add approach and complexities in this existing [code](https://github.com/utkarsh006/LeetCode-Grind/blob/main/MARCH%20CHALLENGES/MAR%2030_Search%20a%202d%20matrix.cpp).

**Comment by utkarsh006** [comment]
@surjyaneeh Work only for one issue at a time.

**Comment by surjyaneeh** [comment]
> @surjyaneeh Work only for one issue at a time.

Okay.
