### ISSUE TITLE
JAN 5 : Palindrome Partitioning

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#68]
## Description
Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.

Example 1:

Input: s = "aab"

Output: [["a","a","b"],["aa","b"]]

- I'll also create a readme file for Jan challenges

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue

**Comment by utkarsh006** [comment]
@Shweta2024 Love your spirit ✔
