### ISSUE TITLE
July 27 : Flatten Binary Tree to Linked List

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#70]
## Description 
Given the root of a binary tree, flatten the tree into a "linked list":

The "linked list" should use the same TreeNode class where the right child pointer points to the next node in the list and the left child pointer is always null.
The "linked list" should be in the same order as a pre-order traversal of the binary tree.

**Comment by Shweta2024** [comment]
@utkarsh006  please assign this issue to me

**Comment by gurjeetsinghvirdee** [comment]
You can't make a PR without assigning!

CC: @utkarsh006

**Comment by Shweta2024** [comment]
> You can't make a PR without assigning!
> 
> CC: @utkarsh006

Sorry,I thought it got assigned to me.
I have closed the pr.I hope its fine now.
