### ISSUE TITLE
Solutions 

### ISSUE THREAD

**Issue by Akanksha-Sen** [utkarsh006/LeetCode-Grind#82]
Add solution links to june, july folder.

**Comment by utkarsh006** [comment]
You can only add to June folder

**Comment by Akanksha-Sen** [comment]
I'll be adding to july folder.

**Comment by utkarsh006** [comment]
Sure Go ahead !!

**Comment by utkarsh006** [comment]
@Akanksha-Sen Close the issue by today midnight.
