### ISSUE TITLE
JUN19 - Search Suggestions System

### ISSUE THREAD

**Issue by coderSuren** [utkarsh006/LeetCode-Grind#85]
### Description

[Search Suggestions System](https://leetcode.com/problems/search-suggestions-system/)

I would like to work on this problem.
pls assign me this issue

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@coderSuren Read the contributing guidelines and then make a contribution :) All the best
