### ISSUE TITLE
Add APR 22 - Design HashMap Solution

### ISSUE THREAD

**Issue by Rakesh9100** [utkarsh006/LeetCode-Grind#89]
### Description

Will add APR 22 - Design HashMap Challenge Solution.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@Rakesh9100 Work on one issue at a time.

**Comment by surjyaneeh** [comment]
@utkarsh006 sir, can you please assign me this issue?
