### ISSUE TITLE
July 29 : Find and Replace Pattern

### ISSUE THREAD

**Issue by Shweta2024** [utkarsh006/LeetCode-Grind#92]
### Description

Given a list of strings words and a string pattern, return a list of words[i] that match pattern. You may return the answer in any order.

A word matches the pattern if there exists a permutation of letters p so that after replacing every letter x in the pattern with p(x), we get the desired word.

Example 1:

Input: words = ["abc","deq","mee","aqq","dkd","ccc"], pattern = "abb"

Output: ["mee","aqq"]

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by Shweta2024** [comment]
@utkarsh006  please assign me this issue

**Comment by utkarsh006** [comment]
@Shweta2024 Your way of presenting your work is appreciable.

**Comment by Shweta2024** [comment]
> @Shweta2024 Your way of presenting your work is appreciable.

Thank you😄
