### ISSUE TITLE
Update March 22, March 26 and March 30 Problems

### ISSUE THREAD

**Issue by surjyaneeh** [utkarsh006/LeetCode-Grind#95]
### Description

Update solutions by adding Approaches, Time and Space Complexities for these problems :

|DATE|PROBLEM|TOPIC|SOLUTION|
|----|-------|-----|--------|
|MARCH 22|[Smallest String With A Given Numeric Value](https://leetcode.com/problems/smallest-string-with-a-given-numeric-value/)|Greedy|[Solution](https://github.com/utkarsh006/LeetCode-Grind/blob/main/MARCH%20CHALLENGES/MAR%2022_Smallest%20String%20With%20A%20Given%20Numeric%20Value.cpp)|
|MARCH 26|[Binary Search](https://leetcode.com/problems/binary-search/)|Binary Search|[Solution](https://github.com/utkarsh006/LeetCode-Grind/blob/main/MARCH%20CHALLENGES/MAR%2026_BINARY%20SEARCH.cpp)|
|MARCH 30|[Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/)|Binary Search, Matrix|[Solution](https://github.com/utkarsh006/LeetCode-Grind/blob/main/MARCH%20CHALLENGES/MAR%2030_Search%20a%202d%20matrix.cpp)|

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/utkarsh006/LeetCode-Grind/blob/main/Guidelines.md) of this project.

**Comment by utkarsh006** [comment]
@surjyaneeh Nice Initiative !! Go Ahead
